FORMAT: 1A
HOST: https://book-a-meal-app-andela.herokuapp.com/

# Book-A-Meal

Book-a-meal API is a simple API that can be used to build a simple online restaurant application

## User [/auth/]
### Signup to the Application [POST /auth/signup]
You can edit to change the details you want to signup with. The fields required are full name, email, phone number, password and address.

+ Request (application/json)

    + Body

            {
                "fullName": "Alex james",
                "email": "alexjames@gmail.com",
                "phoneNumber": 07037827892,
                "password": "testing",
                "address": "124, Express road, Lagos State"
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "User successfully created",
                "data": {
                    "id": "c3b7c8ec-1b5b-409d-94d4-fe0c512c227a",
                    "fullName": "Alex James",
                    "email": "alexjames@gmail.com",
                    "phoneNumber": "07037827892",
                    "role": "customer",
                    "address": "124, Express road, Lagos State"
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"
            }

+ Request (application/json)

    + Body

            {
                "fullName": " Alex 123",
                "email": "alexjames@gmail.com",
                "phoneNumber": 07037827892,
                "password": "testing",
                "address": "124, Express road, Lagos State"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid name",
            }

+ Request (application/json)

    + Body

            {
                "fullName": "Alex James",
                "email": "alexjamesgmail",
                "phoneNumber": 07037827892,
                "password": "testing",
                "address": "124, Express road, Lagos State"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid email address",
            }
            
+ Request (application/json)

    + Body

            {
                "fullName": "Alex James",
                "email": "alexjames@gmail.com",
                "phoneNumber": "0703782789yu",
                "password": "testing",
                "address": "124, Express road, Lagos State"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid phone number",
            }
            
+ Request (application/json)

    + Body

            {
                "fullName": "Alex James",
                "email": "alexjames@gmail.com",
                "phoneNumber": 07037827898,
                "password": "testing <>",
                "address": "124, Express road, Lagos State"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid password",
            }
            
+ Request (application/json)

    + Body

            {
                "fullName": "Alex James",
                "email": "alexjames@gmail.com",
                "phoneNumber": 07037827898,
                "password": "testing",
                "address": "124, Express road, Lagos State <=>"
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid address",
            }

+ Request (application/json)

    + Body

            {
                "fullName": "Mary Janes",
                "email": "alexjames@gmail.com",
                "phoneNumber": 07037827898,
                "password": "testing",
                "address": "124, Express road, Lagos State"
            }

+ Response 409 (application/json)

    + Body

            {
                "message": "A User already exist with this email address",
            }

### Signin to the Application [POST /auth/login]
You can change the details to match what you signed up with. Only the email address and password is required.

+ Request (application/json)

    + Body

            {
                "email": "alexjames@gmail.com",
                "password": "testing",
            }

+ Response 200 (application/json)

    + Body

            {
                "message": "User successfully created",
                "data": {
                    "id": "c3b7c8ec-1b5b-409d-94d4-fe0c512c227a",
                    "fullName": "Alex James",
                    "email": "alexjames@gmail.com",
                    "phoneNumber": "07037827892",
                    "role": "customer",
                    "address": "124, Express road, Lagos State"
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"
            }

+ Request (application/json)

    + Body

            {
                "email": "alexjamesgmail.com",
                "password": "testing",
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid email address"
            }

+ Request (application/json)

    + Body

            {
                "email": "alexjames@gmail.com",
                "password": "  ",
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid password"
            }

+ Request (application/json)

    + Body

            {
                "email": "alexjames@gmail.com",
                "password": "testin",
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "Email or password is incorrect"
            }

+ Request (application/json)

    + Body

            {
                "email": "maryjane@gmail.com",
                "password": "testin",
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "Account does not exist. Please signup to continue"
            }

### Upgrade your role from Customer to Caterer [PUT /auth/update]
You can upgrade your role from customer to caterer. You need to provide the token sent to you when you signed up or logged in.

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 200 (application/json)

    + Body

            {
                "message": "Update successful",
                "data": {
                    "id": "c3b7c8ec-1b5b-409d-94d4-fe0c512c227a",
                    "fullName": "Alex James",
                    "email": "alexjames@gmail.com",
                    "phoneNumber": "07037827892",
                    "role": "caterer",
                    "address": "124, Express road, Lagos State"
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 409 (application/json)

    + Body

            {
                "message": "You are already a caterer"}
            }

### Refresh Token [POST /auth/token]
You can refresh you token if you visit the application consistently

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 201 (application/json)

    + Body

            {
                "message": "Token refreshed successfully",
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

## Meal [/meals/]
### Add the meals - Caterer [POST]
The details required includes meal name, meal price and the image of the meal.You must be a caterer before you can add a meal

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 201 (application/json)

    + Body

            {
                "message": "New meal added successfully",
                "data": {
                    "id": "593c9d41-4c24-4ea1-949e-c1f30b3af0a4",
                    "isDeleted": false,
                    "name": "Rice and Beans",
                    "price": 500,
                    "imageURL": "www.image.com/link"
                    "userId": "c3b7c8ec-1b5b-409d-94d4-fe0c512c227a",
                    "updatedAt": "2018-05-17T06:34:29.694Z",
                    "createdAt": "2018-05-17T06:34:29.694Z"
                 }
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "User account does not exist",
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }
            
+ Request (application/json)

    + Body

            {
                "name": "Rice 12345",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid meal name"
            }

+ Request (application/json)

    + Body

            {
                "name": "",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Meal Name must be between 1 to 40 characters long"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": "500df",
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid meal price"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link=<>"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid image URL"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link"
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Meal already exist"
            }

### Get a list of all the meals you have added - Caterer [GET]
You have to provide the a valid token as its only caterer's that can access this route.

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "82a712ab-fd6e-4b68-bc63-c34f5f1ba7f1",
                    "name": "Rice and Beans
                    "imageURL": "www.image.com/jiu7i89jk",
                    "price": 500,
                },
                {
                    "id": "82a712ab-fd6e-4b68-bc63-c34f5f1ba7f1",
                    "name": "Potato Chips",
                    "imageURL": "www.image.com/jiu7i89jk",
                    "price": 1600,
                }
            ]
        }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "You have not added any meal",
            }

### Modify a meal - Caterer[PUT /meals/{meal_id}]
You can modify a meal by sending the mealid as a parameter, the properties you want to update as well as your token

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 800,
                "imageURL": "www.image.com/link"
            }

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify
        
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 200(application/json)

    + Body

            {
                "data": {
                    "id": "cbe3af6b-2007-479f-88ce-d2b91377f599",
                    "name": "Potato Chips",
                    "imageURL": "www.image.com/widj76ud",
                    "price": "3500",
                    "userId": "fc103acd-6c52-4005-b903-c6ffcaade340",
                    "isDeleted": false,
                    "createdAt": "2018-05-16T09:50:46.473Z",
                    "updatedAt": "2018-05-16T10:01:20.366Z"
                }
            }
            
+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 800,
                "imageURL": "www.image.com/link"
            }

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 800,
                "imageURL": "www.image.com/link"
            }

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 800,
                "imageURL": "www.image.com/link"
            }

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice 12345",
                "price": 500,
                "imageURL": "www.image.com/link"
            }
    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid meal name"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": "500df",
                "imageURL": "www.image.com/link"
            }
            
    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid meal price"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 500,
                "imageURL": "www.image.com/link=<>"
            }
    
    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "Please provide a valid image URL"
            }

+ Request (application/json)

    + Body

            {
                
            }
    
    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "You have not provided any details to update"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 700,
                "imageURL": "www.image.com/link=<>"
            }
    
    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 409 (application/json)

    + Body

            {
                "message": "A meal with this name already exist"
            }

+ Request (application/json)

    + Body

            {
                "name": "Rice and Beans",
                "price": 700,
                "imageURL": "www.image.com/link=<>"
            }
    
    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlGMM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 401 (application/json)

    + Body

            {
                "message": "You can not modify this meal"
            }

### Delete a meal - Caterer [DELETE]
You can modify a meal by sending the mealid as a parameter as well as your token

+ Request (application/json)

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify
        
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 200(application/json)

    + Body

            {
               "message": "Meal has been deleted successfully"
            }

+ Request (application/json)

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "This meal does not exist in the database",
            }

+ Request (application/json)

    + Parameters

        + meal_id (UUID) - ID of the meal you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You are not authorized to delete this meal",
            }

## Menu [/menu]
### Create a menu - Caterer [POST]
You simply send in the ids of the meals you want to add along with your token. You must be a caterer to access this route.

+ Request (application/json)

    + Body

            {
                "meals": ["8f17a141-7c02-40f5-8c28-c8c520f9946d", "593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 201 (application/json)

    + Body

            {
                "message": "Menu created",
                "data": {
                    "id": "bd7596b2-42b5-43e0-9655-3da1f932738f",
                    "userId": "bfb52e81-7a7c-4858-8f31-194d85531be2",
                    "date": "Wed May 16 2018",
                    "updatedAt": "2018-05-16T10:14:15.183Z",
                    "createdAt": "2018-05-16T10:14:15.183Z"
                }
            }

+ Request (application/json)

    + Body

            {
                "meals": ["8f17a141-7c02-40f5-8c28-c8c520f9946d", "593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Body

            {
                "meals": ["8f17a141-7c02-40f5-8c28-c8c520f9946d", "593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Body

            {
                "meals": ["8f17a141-7c02-40f5-8c28-c8c520f9946d", "593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Body

            {
                
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "You have not provided any details",
            }

+ Request (application/json)

    + Body

            {
                "meals": ["8f17a141-7c02-40f5-8c28-c8c520f9949d", "593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Some selected meals does not exist",
            }

+ Request (application/json)

    + Body

            {
                "meals": ["8f17a141-7c02-40f5-8c28-c8c520f9949e"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 200 (application/json)

    + Body

            {
                "message": "Menu has been updated",
            }

### Get the menu that has been created - Customer [GET /menu/customer]
You have to provide the a valid token.

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "bd7596b2-42b5-43e0-9655-3da1f932738f",
                    "date": "Wed May 16 2018",
                    "catererId": "bfb52e81-7a7c-4858-8f31-194d85531be2",
                    "meals": [
                        {
                            "name": "Rice and Beans",
                            "imageURL": "www.image.com/jiu7i89jk",
                            "price": 800,
                            "menuItems": {
                                "createdAt": "2018-05-16T10:14:15.405Z",
                                "updatedAt": "2018-05-16T10:14:15.405Z",
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "menuId": "bd7596b2-42b5-43e0-9655-3da1f932738f"
                            }
                        },
                        {
                            "name": "Potato Chips",
                            "imageURL": "www.image.com/jiu7i89jk",
                            "price": 1600,
                            "menuItems": {
                                "createdAt": "2018-05-16T10:14:15.405Z",
                                "updatedAt": "2018-05-16T10:14:15.405Z",
                                "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                                "menuId": "bd7596b2-42b5-43e0-9655-3da1f932738f"
                            }
                        }
                    ],
                    "caterer": {
                        "fullName": "Alex James",
                        "email": "alexjames@gmail.com"
                    }
                }
            ]
        }
 
 + Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "The menu for today has not been set yet",
            }

### Get the menu that has been created - Caterer [GET /menu/caterer]
You need to be a caterer to access this route. You need to provide a valid token.

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 200 (application/json)

    + Body

            {
                "data": {
                    "id": "bd7596b2-42b5-43e0-9655-3da1f932738f",
                    "date": "Wed May 16 2018",
                    "userId": "bfb52e81-7a7c-4858-8f31-194d85531be2",
                    "createdAt": "2018-05-16T10:14:15.183Z",
                    "updatedAt": "2018-05-16T10:14:15.183Z",
                    "meals": [
                        {
                            "name": "Rice and Beans",
                            "imageURL": "www.image.com/jiu7i89jk",
                            "price": 800,
                            "menuItems": {
                                "createdAt": "2018-05-16T10:14:15.405Z",
                                "updatedAt": "2018-05-16T10:15:15.405Z",
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "menuId": "bd7596b2-42b5-43e0-9655-3da1f932738f"
                            }
                        }
                    ]
                }
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "The menu for today has not been set yet",
            }

### Remove a meal or many meals from the menu - Caterer [DELETE]
You can remove a meal or multiple meals from the menu. You should provide the meal id as well as your token.

+ Request (application/json)

    + Body

            {
                "meals": ["593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }
        
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 200(application/json)

    + Body

            {
                "message": "Menu has been updated",
                "data": {
                    "id": "bd7596b2-42b5-43e0-9655-3da1f932738f",
                    "userId": "bfb52e81-7a7c-4858-8f31-194d85531be2",
                    "date": "Wed May 16 2018",
                    "updatedAt": "2018-05-16T10:15:15.183Z",
                    "createdAt": "2018-05-16T10:14:15.183Z"
                }
            }

+ Request (application/json)

    + Body

            {
                "meals": ["593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Body

            {
                "meals": ["593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Body

            {
                "meals": ["593c9d41-4c24-4ea1-949e-c1f30b3af0a4"]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Body

            {
                
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "You have not provided any details",
            }

## Order [/order]
### Place an Order - Customer [POST]
You need to provide the meal id, quantity, a delivery address if different from the one you signed up with.

+ Request (application/json)

    + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    {
                        "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                        "quantity": 10
                    },
                    {
                        "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                        "quantity": 4
                    }
                ]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 201 (application/json)

    + Body

            {
                "message": "Order Placed successfully",
                "data": {
                    "id": "d65a1b90-ea1c-424c-a0d0-3fe7769a5b54",
                    "date": "Wed May 16 2018",
                    "isDeleted": false,
                    "userId": "9253f41c-95ad-4e31-aefb-25c6541c25a4",
                    "time": "11:19",
                    "deliveryAddress": "124B, Allen Way, Ikeja",
                    "updatedAt": "2018-05-16T10:19:43.307Z",
                    "createdAt": "2018-05-16T10:19:43.307Z"
                }
            }

+ Request (application/json)

   + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    {
                        "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                        "quantity": 10
                    },
                    {
                        "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                        "quantity": 4
                    }
                ]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    {
                        "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                        "quantity": 10
                    },
                    {
                        "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                        "quantity": 4
                    }
                ]
            }

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

   + Body

            {
                
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 400 (application/json)

    + Body

            {
                "message": "You have not provided any details"
            }
            
+ Request (application/json)

   + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    {
                        "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                        "quantity": 10
                    },
                    {
                        "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                        "quantity": 4
                    }
                ]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "You cannot place an order yet"
            }

+ Request (application/json)

   + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    {
                        "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                        "quantity": 10
                    },
                    {
                        "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                        "quantity": 4
                    }
                ]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "You cannot place any more order today"
            }

+ Request (application/json)

   + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    
                ]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "You have not provided any meal"
            }

+ Request (application/json)

   + Body

            {
                "deliveryAddress": "124B, Allen Way, Ikeja",
                "meals": [
                    {
                        "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                        "quantity": 10
                    },
                    {
                        "mealId": "7c205a70-52f1-4ada-883c-6745f90f0033",
                        "quantity": 4
                    }
                ]
            }

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 404 (application/json)

    + Body

            {
                "message": "The menu for today has not been set yet"
            }

### Get the order that have been placed - Customer [GET /order/customer]
You have to provide the a valid token.

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 200 (application/json)

        {
            "message": "You have placed the following orders",
            "data": [
                {
                    "id": "d65a1b90-ea1c-424c-a0d0-3fe7769a5b54",
                    "date": "Wed May 16 2018",
                    "time": "11:19",
                    "userId": "9253f41c-95ad-4e31-aefb-25c6541c25a4",
                    "deliveryAddress": null,
                    "isDeleted": false,
                    "createdAt": "2018-05-16T10:19:43.307Z",
                    "updatedAt": "2018-05-16T11:06:52.812Z",
                    "meals": [
                        {
                            "id": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                            "name": "Rice and Beans",
                            "imageURL": "www.image.com/jiu7i89jk",
                            "price": 800,
                            "isDeleted": false,
                            "orderItems": {
                                "quantity": 5,
                                "createdAt": "2018-05-16T10:57:52.554Z",
                                "updatedAt": "2018-05-16T11:06:53.019Z",
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "orderId": "d65a1b90-ea1c-424c-a0d0-3fe7769a5b54"
                            }
                        }
                    ],
            ],
            "totalExpenses": 4000
        }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 404 (application/json)

        {
            "message": "You have not placed any order yet"
        }
  
### Get all orders that has been place to you - Caterer [GET /order/caterer]
You need to provide a valid token.

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 200 (application/json)

        {
            "message": "You have the following orders",
            "data": [
                {
                    "id": "d65a1b90-ea1c-424c-a0d0-3fe7769a5b54",
                    "date": "Wed May 16 2018",
                    "time": "11:19",
                    "userId": "9253f41c-95ad-4e31-aefb-25c6541c25a4",
                    "deliveryAddress": null,
                    "isDeleted": false,
                    "createdAt": "2018-05-16T10:19:43.307Z",
                    "updatedAt": "2018-05-16T11:06:52.812Z",
                    "meals": [
                        {
                            "id": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                            "name": "Akara and pap",
                            "imageURL": "www.image.com/jiu7i89jk",
                            "price": 1500,
                            "isDeleted": false,
                            "orderItems": {
                                "quantity": 12,
                                "createdAt": "2018-05-16T10:57:52.554Z",
                                "updatedAt": "2018-05-16T11:06:53.019Z",
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "orderId": "d65a1b90-ea1c-424c-a0d0-3fe7769a5b54"
                            }
                        }
                    ],
                    "user": {
                        "id": "9253f41c-95ad-4e31-aefb-25c6541c25a4",
                        "fullName": "Samuel James",
                        "email": "samjames@gmail.com",
                        "phoneNumber": "07037827892",
                        "address": "124, Express road, Lagos State"
                    }
                }
            ],
            "totalSales": 18000
        }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNWW5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOYW1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"


+ Response 404 (application/json)

        {
            "message": "You don't have any order yet"
        }

### Modify an Order - Customer [PUT /order/{order_id}]
You need to provide the order id, meal id, quantity, a delivery address if different from the one you signed up with.

+ Request (application/json)

    + Body

            {
                "meals": [
                            {
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "quantity": 12
                            }
                        ]
            }

    + Parameters

        + order_id (UUID) - ID of the order you want to modify
    
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 200 (application/json)

    + Body

            {
                "message": "Order Modified successfully",
                "data": {
                    "id": "d65a1b90-ea1c-424c-a0d0-3fe7769a5b54",
                    "date": "Wed May 16 2018",
                    "time": "11:19",
                    "userId": "9253f41c-95ad-4e31-aefb-25c6541c25a4",
                    "isDeleted": false,
                    "createdAt": "2018-05-16T10:19:43.307Z",
                    "updatedAt": "2018-05-16T11:06:52.812Z"
                }
            }

+ Request (application/json)

    + Body

            {
                "meals": [
                            {
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "quantity": 12
                            }
                        ]
            }

    + Parameters

        + order_id (UUID) - ID of the order you want to modify
        
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "Invalid Token"
            }

+ Request (application/json)

    + Body

            {
                "meals": [
                            {
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "quantity": 12
                            }
                        ]
            }

    + Parameters

        + order_id (UUID) - ID of the order you want to modify

    + Headers

            Authorization: ""

+ Response 403 (application/json)

    + Body

            {
                "message": "Please provide a valid token"
            }

+ Request (application/json)

    + Body

            {
                "meals": [
                            {
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "quantity": 12
                            }
                        ]
            }

    + Parameters

        + order_id (UUID) - ID of the order you want to modify
    
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 403 (application/json)

    + Body

            {
                "message": "You don't have access to use this route",
            }

+ Request (application/json)

    + Body

            {
                "meals": [
                            {
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "quantity": 12
                            }
                        ]
            }

    + Parameters

        + order_id (UUID) - ID of the order you want to modify
    
    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 401 (application/json)

    + Body

            {
                "message": "Order not found",
            }
            
+ Request (application/json)

    + Body

            {
                "meals": [
                            {
                                "mealId": "4ef65ce5-b64a-45ca-9c02-c18857894dc2",
                                "quantity": 12
                            }
                        ]
            }

    + Parameters

        + order_id (UUID) - ID of the order you want to modify

    + Headers

            Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVYU9.eyJpZCI6ImMzYjdjOGVjLTFiNWItNDA5ZC05NGQ0LWZlMGM1MTJjMjI3YSIsImZ1bGxOQQ1lIjoiQWxleCBKYW1lcyIsImVtYWlsIjoiYWxleGphbWVzQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDcwMzc4Mjc4OTIiLCJyb2xlIjoiY3VzdG9tZXIiLCJhZGRyZXNzIjoiMTI0LCBFeHByZXNzIHJvYWQsIExhZ29zIFN0YXRlIiwiaWF0IjoxNTI2NTM4NjYzLCJleHAiOjE1MjY2MjUwNjN9.yCehS5feOdohmU0V_vTLdba0sjmaSDXu1VsVzhqjlfk"

+ Response 401 (application/json)

    + Body

            {
                "message": "You can not modify this order",
            }